<a href="https://colab.research.google.com/github/EngMdarwish/HakerRank/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1- Shape and Reshape**
You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [9]:
import numpy as np
if __name__ == '__main__':
  try:
    _input=list(map(int, input().split()))
    if len(_input)==9:
      x=np.array(_input)
      y=np.reshape(x,(3,3))
      print(y)
    else:
      print('Please enter 9 integers')
  
  except :
    print('Please Enter valid nine integers')

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**2- Transpose and Flatten**
You are given a nXm integer array matrix with space separated elements ( n= rows and  m= columns).
Your task is to print the transpose and flatten results.

The first line contains the space separated values of N  and M.
The next N lines contains the space separated elements of M columns.

In [39]:
import numpy as np
if __name__ == '__main__':
  try:
    n,m=map(int,input().split())
    arr=np.array([input().split() for i in range(n)],dtype=np.int64)
    print(arr.transpose())
    print(arr.flatten())
  except ValueError as e:
    print(e)

  

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


**3- Concatenate**
You are given two integer arrays of size NXP and MXP (N & N are rows, and P is the column). Your task is to concatenate the arrays along axis 0 .

Input Format

The first line contains space separated integers N,M  and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the  P columns.

Output Format

Print the concatenated array of size(N+M) X P.

In [41]:
import numpy as np
if __name__ == '__main__':
  try:
    n,m,p=map(int,input().split())
    arr1=np.array([input().split() for i in range(n)],dtype=np.int64)
    arr2=np.array([input().split() for i in range(m)],dtype=np.int64)
    arr=np.concatenate((arr1,arr2),axis=0)
    print(arr)
  except ValueError as e:
    print(e)



4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


**4- Zeros and Ones**
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Constraints

1<= eachintteger <=3

Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

In [61]:
import numpy as np
if __name__ == '__main__':
  try:
    t=tuple(map(int,input().split()))
    if 1<=t[0]<=3 and 1<=t[1]<=3 and 1<=t[1]<=3:
      arr1=np.zeros(t,dtype=np.int)
      arr2=np.ones(t,dtype=np.int)
      print(arr1)
      print(arr2)
    else:
      print('1<= eachinteger <=3')
  except ValueError as e:
    print(e)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


**5- Eye and Identity**

Task

Your task is to print an array of size NXM with its main diagonal elements as 1's and 0's everywhere else.



Input Format

A single line containing the space separated values of N and M.
N denotes the rows.
M denotes the columns.

Output Format

Print the desired NXM array.


In [64]:
import numpy as np
if __name__ == '__main__':
  try:
    n , m=map(int,input().split())
    np.set_printoptions(legacy='1.13')
    print(np.eye(n,m,k=0))
  except ValueError as e:
    print(e)

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**6- Array Mathematics**
You are given two integer arrays,  A and B  of dimensions NXM.
Your task is to perform the following operations:

Add 
Subtract 
Multiply 
Integer Division 
Mod 
Power 

In [71]:
import numpy as np
if __name__ == '__main__':
  try:
    n,m = map(int,input().split())
    a,b=(np.array([input().split() for i in range(n)],dtype=np.int64) for t in range(2))
    print("{}\n{}\n{}\n{}\n{}\n{}".format(a+b,a-b,a*b, a//b,a%b,a**b))
  except ValueError as e:
    print(e)



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
